export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";

export const FILTER_PRODUCTS_BY_PRICE = "FILTER_PRODUCTS_BY_PRICE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";

export const ADD_TO_CART = "ADD_TO_CART";
export const ALTER_PRICE = "ALTER_PRICE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const CLEAR_CART = "CLEAR_CART";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
